app:
  build: .

api:
  extends:
    service: app
  command: python shapaozi/app.py
  restart: always
  net: "host"

crawler:
  extends:
    service: app
  command: python shapaozi/crawler.py
  restart: always
  cpu_shares: 512
  net: "host"

mongo:
  image: mongo:3.2.1
  cpu_shares: 4096
  restart: always
  ports:
    - "127.0.0.1:27017:27017"

